language: php

jobs:
  include:
    - stage: "Split Components"
      php: 7.2
      install:
      - travis_retry composer install
      script:
      - git fetch --unshallow
      - ./dev/google-cloud split $TRAVIS_TAG

stages:
  - name: "Split Components"
    if: (tag IS present)
